name: simple_rich_text
description: Display a Dart string in Flutter using simple rich text characters.
version: 2.0.47        #NOEDIT
homepage: https://github.com/remoteportal/simple_rich_text

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
